### ISSUE TITLE
Node js Error: spawn ENOENT when npm-publish

### ISSUE THREAD

**Issue by vinhnghi223** [acierto/gulp-release#1]
My node version is v0.10.24. And here is what I got when typing gulp release.

![childprocess issue](https://cloud.githubusercontent.com/assets/2405899/12572516/1fd90f74-c3f6-11e5-9e8e-5ba565b0ccc0.PNG)

**Comment by acierto** [comment]
Hey, sorry didn't check the repository for a while :)
I can't say much about the issue which you experienced with. I suggest to try to use the latest Node.js version

**Comment by lawrence-pressinnov** [comment]
got the exact same issue here
using node v4.2.6 on windows
any idea what is happening?
