### ISSUE TITLE
Bump commit message not use the real new version number

### ISSUE THREAD

**Issue by patou** [acierto/gulp-release#2]
When you release and bump the version with the same commande (gulp release), commit message are :
* Build version 1.0.1
* Bumps version to v1.0.1

The last commit message must be Bumps version to v1.0.2

I think it's this code :
`require(file.path).version`

Require keep in cache the file and not load the last edit.
http://stackoverflow.com/questions/22645779/javascript-get-package-json-data-in-gulpfile-js

**Comment by acierto** [comment]
No, that's because it first releases and then bumps the version. If you want to bump and then release you need to use another task. I included it into the latest version. You need to run "gulp bump-release" instead of "gulp release"

**Comment by patou** [comment]
No, I want tu release and next bump to the next version.
The version in the package.xml and bower.xml is not the same as in the commit message.

**Comment by patou** [comment]
For exemple, if you look your commit :
https://github.com/acierto/gulp-release/commit/facfdf42a7d53a3de8cfd54d69cdafbd3cfb9dc9
The commit message are Bumps version to v1.0.10
But the version in the package.json is v1.0.11

**Comment by acierto** [comment]
In this plugin 2 approaches how you can release.

1) Your package.json has version v1.0.0, you don't have any tag in GitHub, and you want to release it and bump to v1.0.1. You run **gulp release** - package.json modifies to v1.0.1 (future version for release) and you have tag in GitHub as v1.0.0

2) Your package.json has version v1.0.0, you have already tag in GitHub as v1.0.0 and you want to release v1.0.1. You run **gulp bump-release** and you have in GitHub version v1.0.1 and your package.json contains after it v1.0.1 (current version)

What you want is second approach, where package.json contains currently released version.

**Comment by acierto** [comment]
Regarding not synchronised version in package.json and bower.json is fixed in v1.1.1. Now the base is package.json, other files (bower.json & manifest.json) are synchronised based on it

**Comment by patou** [comment]
I use the first approach.
I just report a bug with the required("package.json").
Your last plugin version seems to correct it.
Before your correction, the commit with the bumps, the version in the commit message was not the version setted in the package.json (et others).

Thanks.
