### ISSUE TITLE
Build metadata or pre-release are not supported in generated version number

### ISSUE THREAD

**Issue by jsyrjala** [acierto/gulp-release#3]
I'd like to make version numbers such as `1.0.1+firefox-fix` or `1.0.1-gamma` and that doesn't seem to be supported by gulp-release, even though both are allowed by semver, see http://semver.org/#spec-item-10 and http://semver.org/#spec-item-9

Syntax to allow could be e.g.
```
gulp bump-release --pre-release gamma
gulp bump-release --build-metadata firefox-fix
```

**Comment by acierto** [comment]
With gulp-release-it@v.1.1.3 you can do

for example your current version is **1.1.0** and you run
`gulp bump-release --pre-release gamma`
and you will have as a result **1.1.0-gamma.0**
