### ISSUE TITLE
Cannot overwrite task pre-tag-and-push in Gulp 4

### ISSUE THREAD

**Issue by kuntergunt** [acierto/gulp-release#7]
Looks like Gulp 4 makes dependencies during runtime. Redefining the task pre-tag-and-push does not use the redefined task.

Try this:
gulp.task('pre-tag-and-push', function (cb) {
    console.log('task overwritten again');
    cb();
});
gulp.task('subtask', function (cb) {
    console.log('subtask 1');
    cb();
});
gulp.task('maintask1', gulp.series('subtask', function (cb) {
    console.log('maintask 1');
    cb();
}));
gulp.task('subtask', function (cb) {
    console.log('subtask 2');
    cb();
});

results in

console: gulp maintask1
subtask 1
maintask 1

console: gulp maintask2
subtask 2
maintask 2

**Comment by acierto** [comment]
Hi man,
The fix is applied for this problem for Gulp 4, you can find it in **version 2.0.8**.
The approach is changed now and instead of using gulp-appfy-tasks plugin, there is a native registry approach.

```
    import util from 'util';
    import gulp from 'gulp';
    import {DefaultReleaseRegistry, release} from 'gulp-release-it';
    
    util.inherits(CustomGulpReleaseRegistry, DefaultReleaseRegistry);
    
    function CustomGulpReleaseRegistry() {
        DefaultReleaseRegistry.call(this);
    }
    
    CustomGulpReleaseRegistry.prototype.init = function (takerInst) {
        takerInst.task('pre-tag-and-push', function (cb) {
            console.log('i can override default task definition');
            cb();
        });
    };
    
    release(gulp, [new CustomGulpReleaseRegistry()]);

```
You can find this snippet of the working code also in the documentation. 

Be aware that you need to call a bit differently the main task.

```
import {release} from 'gulp-release-it';
release(gulp);
```
instead of

```
import gulpReleaseIt from 'gulp-release-it';
gulpReleaseIt(gulp);
````
